min_version = "2025.2.3"

[tools]
node = "20.17.0"

[env]
_.path = ["./node_modules/.bin"]

[tasks.setup]
run = ["mise install", "corepack enable", "pnpm install --frozen-lockfile"]

[tasks.build]
run = "turbo run build --no-daemon"

[tasks.check]
run = "turbo run check:format check:lint check:type check:unused --no-daemon --continue"

[tasks.fix]
run = "turbo run fix:lint fix:format --no-daemon"
