min_version = "2025.2.3"

[tools]
node = "22.20.0"
claude = "2.0.1"
"npm:ccusage" = "17.1.1"

[env]
_.path = ["./node_modules/.bin"]

[tasks.setup]
run = ["mise install", "corepack enable", "pnpm install --frozen-lockfile"]

[tasks.build]
run = "turbo run build"

[tasks.check]
run = "turbo run check:format check:lint check:type check:unused --continue"

[tasks.fix]
run = "turbo run fix:lint fix:format"
