min_version = "2025.2.3"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[tools]
"npm:ccusage" = "18.0.5"

[env._]
path = ["{{config_root}}/node_modules/.bin"]

[tasks.setup]
run = ["mise install", "corepack enable", "pnpm install --frozen-lockfile"]

[tasks.build]
run = "turbo run build"

[tasks.check]
run = "turbo run check:format check:lint check:type check:unused --continue"

[tasks.fix]
run = "turbo run fix:lint fix:format"
