name: Setup toolchain

description: Setup toolchain

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        registry-url: https://registry.npmjs.org
        cache: pnpm
    - shell: bash
      run: npm install --global npm@latest
    - uses: actions/cache@v4
      with:
        path: .turbo/cache
        key: turbo-${{ runner.os }}-${{ github.sha }}
        restore-keys: turbo-${{ runner.os }}-
    - shell: bash
      run: echo "TURBO_CACHE_DIR=$(pwd)/.turbo/cache" >> $GITHUB_ENV
