name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TOUCHSPOT_GHA_APP_ID }}
          private_key: ${{ secrets.TOUCHSPOT_GHA_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - uses: ./.github/actions/setup-toolchain
      - run: pnpm install --frozen-lockfile
      - run: mise run fix
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: autofix"

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-toolchain
      - run: pnpm install --frozen-lockfile
      - run: mise run check
